//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bài_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phim
    {
        public int MaPhim { get; set; }
        public string TenPhim { get; set; }
        public string HinhPhim { get; set; }
        public Nullable<int> NumberLike { get; set; }
    }
}
